FROM node:18-alpine

WORKDIR /shared

# Kopiowanie plików do instalacji zależności
COPY package*.json ./
COPY tsconfig*.json ./

# Instalacja zależności
RUN npm install

# Kopiowanie kodu źródłowego
COPY . .

# Budowanie modułu shared
RUN npm run build